# Generated by Django 3.1.5 on 2021-02-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('caption', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'Meme',
            },
        ),
    ]
